/*
 *
 *  * Developed by - mGunawardhana
 *  * Contact email - mrgunawardhana27368@gmail.com
 *  * what's app - 071 - 9043372
 *
 */
let baseURL = "http://localhost:8080/deployApp/";

loadAllCustomersToCombo();
loadAllItemToCombo();

let autoGeneratedOrderId = 1;
$('#txtOrderID').val('O00-00' + autoGeneratedOrderId);

/** loading all customer id's in to the combo */
function loadAllCustomersToCombo() {
    $('#orderCustomerID').empty();

    $.ajax({
        url: baseURL + "customer",
        method: "GET",
        dataType: "json",
        success: function (res) {
            for (let customer of res.data) {
                $("#orderCustomerID").append(`<option>${customer.id}</option>`)
            }
        },
        error: function (error) {
            let message = JSON.parse(error.responseText).message;
            alert(message);
        }
    });
}

/** loading all item id's in to the combo */
function loadAllItemToCombo() {
    $('#itemCodeCombo').empty();
    $.ajax({
        url: baseURL + "item",
        method: "GET",
        dataType: "json",
        success: function (res) {
            for (let item of res.data) {
                $("#itemCodeCombo").append(`<option>${item.itemId}</option>`)
            }
        },
        error: function (error) {
            let message = JSON.parse(error.responseText).message;
            alert(message);
        }
    });
}

/** combo operation on oder id */
$('#orderCustomerID').on('click', function () {
    let customerID = $('#orderCustomerID').val();
    $.ajax({
        url: baseURL + "customer",
        method: "GET",
        dataType: "json",
        success: function (res) {
            for (let customer of res.data) {
                if (customer.id === customerID) {
                    $("#selectCusName").val(customer.name);
                    $("#orderCustomerContact").val(customer.address);
                    $("#orderCustomerAddress").val(customer.contact);
                }
            }
        }
    });
});

/** combo operation on oder id */
$('#itemCodeCombo').on('click', function () {
    $.ajax({
        url: baseURL + "item",
        method: "GET",
        dataType: "json",
        success: function (res) {
            for (let item of res.data) {
                if (item.itemId === $('#itemCodeCombo').val()) {
                    $("#selectItemCode").val(item.itemId);
                    $("#txtItemDescription").val(item.itemName);
                    $("#txtItemPrice").val(item.unitPrice);
                    $("#txtQTYOnHand").val(item.qty);
                }
            }
        }
    });
})

/** add to cart option */


$("#btnAddToTable").on("click",function (){

    let itemId = $('#itemCodeCombo').val();
    let itemName = $('#txtItemDescription').val();
    let unitPrice = $('#txtItemPrice').val();
    let itemQty = $('#txtQty').val();
    let tot = unitPrice * itemQty;

    $("#orderTblBody").append(
        `<tr>
            <td>${itemId}</td>
            <td>${itemName}</td>
            <td>${unitPrice}</td>
            <td>${itemQty}</td>
            <td>${tot}</td>
        </tr>`
    );

    $("#total").val(tot);

});

$('#btnClear').on('click', function () {

});



